In [1]:
import numpy as np

In [5]:
l = [12,3,4,'a',4,3]

In [6]:
arr = np.array(l)

In [7]:
l

[12, 3, 4, 'a', 4, 3]

In [11]:
arr = np.random.randint(100, size = (30))

In [12]:
arr

array([61, 25, 58, 90, 18, 54, 80, 86, 78, 91,  5, 94, 66, 65, 95, 86, 35,
       28, 23, 60, 61, 40, 56, 56, 84,  6, 45, 62, 11, 94])

In [16]:
arr.reshape(5,3,2)

array([[[61, 25],
        [58, 90],
        [18, 54]],

       [[80, 86],
        [78, 91],
        [ 5, 94]],

       [[66, 65],
        [95, 86],
        [35, 28]],

       [[23, 60],
        [61, 40],
        [56, 56]],

       [[84,  6],
        [45, 62],
        [11, 94]]])

In [45]:
s = arr.reshape(15,2)

In [28]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(x[1][2])

6


In [29]:
arr = np.random.randint(100, size=(5,6))

In [30]:
print(arr[2][2])

72


In [31]:
arr

array([[22, 28, 52, 60, 43, 55],
       [74, 98, 63,  9, 96,  1],
       [72, 10, 72, 71, 52, 24],
       [34, 45, 55, 38, 46, 45],
       [70, 87, 18, 54, 29, 88]])

In [34]:
l = list(arr.reshape(3,10))

In [35]:
n = np.array(l)

In [36]:
n

array([[22, 28, 52, 60, 43, 55, 74, 98, 63,  9],
       [96,  1, 72, 10, 72, 71, 52, 24, 34, 45],
       [55, 38, 46, 45, 70, 87, 18, 54, 29, 88]])

In [44]:
n.max()

98

In [46]:
s

array([[22, 28],
       [52, 60],
       [43, 55],
       [74, 98],
       [63,  9],
       [96,  1],
       [72, 10],
       [72, 71],
       [52, 24],
       [34, 45],
       [55, 38],
       [46, 45],
       [70, 87],
       [18, 54],
       [29, 88]])

In [48]:
a = s.reshape(1,30)

In [49]:
a


array([[22, 28, 52, 60, 43, 55, 74, 98, 63,  9, 96,  1, 72, 10, 72, 71,
        52, 24, 34, 45, 55, 38, 46, 45, 70, 87, 18, 54, 29, 88]])

In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

In [51]:
arr

array([1, 2, 3, 4, 5, 6])

In [76]:
arr = np.concatenate((arr1, arr2), axis = 1)

In [90]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
a = np.array([[1,7]])
ar =  np.vstack((arr, a))
m = np.array([[1],[2],[3],[4],[5]])
r =  np.hstack((ar, m))
print(r)

[[1 2 1]
 [3 4 2]
 [5 6 3]
 [7 8 4]
 [1 7 5]]


In [92]:
 a = np.diagonal(5,4)

ValueError: diag requires an array of at least two dimensions